=== ArtemZinkevich/epamCourses/task_5/data/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:complexType name="plantSpecies">
        <xs:sequence>
            <xs:element name="name" type="xs:token"/>
            <xs:element name="soil">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Podsolic"/>
                        <xs:enumeration value="Ground"/>
                        <xs:enumeration value="Sod-Podsolic"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="origin">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="^[A-ZА-Я].*$"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="visual_parameters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="stalk_color" type="xs:string"/>
                        <xs:element name="leaves_color" type="xs:string"/>
                        <xs:element name="average_size" type="xs:positiveInteger"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="growing_tips">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="temperature" type="xs:float"/>
                        <xs:element name="watering" type="xs:positiveInteger"/>
                    </xs:sequence>
                    <xs:attribute name="photophilous" use="required" default="true" type="xs:boolean"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="multiplying">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Leaves"/>
                        <xs:enumeration value="Cuttings"/>
                        <xs:enumeration value="Seeds"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="plant" type="plantSpecies" abstract="true"/>

    <xs:complexType name="greenhousePlant">
        <xs:complexContent>
            <xs:extension base="plantSpecies">
                <xs:attribute name="id" use="required" type="xs:ID"/>
                <xs:attribute name="price" use="optional" type="xs:positiveInteger"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="flower" type="greenhousePlant" substitutionGroup="plant"/>
    <xs:element name="flowers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="flower" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ArtemZinkevich/epamCourses/task_5/data/plants.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema.xsd">
    <flower id="1">
        <name>Rose</name>
        <growing_tips photophilous="true">
            <temperature>20</temperature>
            <watering>20</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <origin>Rome</origin>
        <soil>Ground</soil>
        <visual_parameters>
            <stalk_color>Dark-green</stalk_color>
            <leaves_color>green</leaves_color>
            <average_size>450</average_size>
        </visual_parameters>
    </flower>
    <flower id="2">
        <name>Orchid</name>
        <growing_tips photophilous="true">
            <temperature>25</temperature>
            <watering>200</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <origin>Spain</origin>
        <soil>Podsolic</soil>
        <visual_parameters>
            <stalk_color>green</stalk_color>
            <leaves_color>green</leaves_color>
            <average_size>40</average_size>
        </visual_parameters>
    </flower>
    <flower id="3">
        <name>Tulip</name>
        <growing_tips photophilous="true">
            <temperature>30</temperature>
            <watering>560</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <origin>Iran</origin>
        <soil>Podsolic</soil>
        <visual_parameters>
            <stalk_color>green</stalk_color>
            <leaves_color>green</leaves_color>
            <average_size>35</average_size>
        </visual_parameters>
    </flower>
    <flower id="4">
        <name>Sunflower</name>
        <growing_tips photophilous="true">
            <temperature>25</temperature>
            <watering>200</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <origin>Europe</origin>
        <soil>Podsolic</soil>
        <visual_parameters>
            <stalk_color>green</stalk_color>
            <leaves_color>green</leaves_color>
            <average_size>100</average_size>
        </visual_parameters>
    </flower>
    <flower id="5">
        <name>Sunflower</name>
        <growing_tips photophilous="true">
            <temperature>25</temperature>
            <watering>200</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <origin>Europe</origin>
        <soil>Podsolic</soil>
        <visual_parameters>
            <stalk_color>green</stalk_color>
            <leaves_color>green</leaves_color>
            <average_size>100</average_size>
        </visual_parameters>
    </flower>
    <flower id="6">
        <name>Iris</name>
        <growing_tips photophilous="true">
            <temperature>25</temperature>
            <watering>200</watering>
        </growing_tips>
        <multiplying>Cuttings</multiplying>
        <origin>Europe</origin>
        <soil>Ground</soil>
        <visual_parameters>
            <stalk_color>green</stalk_color>
            <leaves_color>green</leaves_color>
            <average_size>30</average_size>
        </visual_parameters>
    </flower>
    <flower id="7">
        <name>Aconitum</name>
        <growing_tips photophilous="false">
            <temperature>50</temperature>
            <watering>10</watering>
        </growing_tips>
        <multiplying>Leaves</multiplying>
        <origin>Africa</origin>
        <soil>Sod-Podsolic</soil>
        <visual_parameters>
            <stalk_color>brown</stalk_color>
            <leaves_color>green</leaves_color>
            <average_size>10</average_size>
        </visual_parameters>
    </flower>
    <flower id="8">
        <name>Amaranthus</name>
        <growing_tips photophilous="true">
            <temperature>35</temperature>
            <watering>1000</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <origin>Africa</origin>
        <soil>Sod-Podsolic</soil>
        <visual_parameters>
            <stalk_color>green</stalk_color>
            <leaves_color>red</leaves_color>
            <average_size>25</average_size>
        </visual_parameters>
    </flower>
    <flower id="9">
        <name>Anemone</name>
        <growing_tips photophilous="true">
            <temperature>25</temperature>
            <watering>350</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <origin>Greece</origin>
        <soil>Sod-Podsolic</soil>
        <visual_parameters>
            <stalk_color>green</stalk_color>
            <leaves_color>grape</leaves_color>
            <average_size>40</average_size>
        </visual_parameters>
    </flower>
    <flower id="10">
        <name>Camelia</name>
        <growing_tips photophilous="true">
            <temperature>20</temperature>
            <watering>200</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <origin>America</origin>
        <soil>Podsolic</soil>
        <visual_parameters>
            <stalk_color>green</stalk_color>
            <leaves_color>green</leaves_color>
            <average_size>35</average_size>
        </visual_parameters>
    </flower>
    <flower id="11">
        <name>Chrysantemum</name>
        <growing_tips photophilous="true">
            <temperature>27</temperature>
            <watering>800</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <origin>Asia</origin>
        <soil>Podsolic</soil>
        <visual_parameters>
            <stalk_color>green</stalk_color>
            <leaves_color>green</leaves_color>
            <average_size>40</average_size>
        </visual_parameters>
    </flower>
    <flower id="12">
        <name>Daisy</name>
        <growing_tips photophilous="true">
            <temperature>32</temperature>
            <watering>300</watering>
        </growing_tips>
        <multiplying>Leaves</multiplying>
        <origin>Africa</origin>
        <soil>Sod-Podsolic</soil>
        <visual_parameters>
            <stalk_color>dark-green</stalk_color>
            <leaves_color>green</leaves_color>
            <average_size>20</average_size>
        </visual_parameters>
    </flower>
    <flower id="13">
        <name>Delphinium</name>
        <growing_tips photophilous="true">
            <temperature>19</temperature>
            <watering>250</watering>
        </growing_tips>
        <multiplying>Cuttings</multiplying>
        <origin>Greece</origin>
        <soil>Sod-Podsolic</soil>
        <visual_parameters>
            <stalk_color>green</stalk_color>
            <leaves_color>green</leaves_color>
            <average_size>24</average_size>
        </visual_parameters>
    </flower>
    <flower id="14">
        <name>Forget Me Not</name>
        <growing_tips photophilous="true">
            <temperature>25</temperature>
            <watering>250</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <origin>Greece</origin>
        <soil>Sod-Podsolic</soil>
        <visual_parameters>
            <stalk_color>green</stalk_color>
            <leaves_color>green</leaves_color>
            <average_size>8</average_size>
        </visual_parameters>
    </flower>
    <flower id="15">
        <name>Gladiolus</name>
        <growing_tips photophilous="true">
            <temperature>30</temperature>
            <watering>200</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <origin>South Africa</origin>
        <soil>Ground</soil>
        <visual_parameters>
            <stalk_color>light-green</stalk_color>
            <leaves_color>green</leaves_color>
            <average_size>70</average_size>
        </visual_parameters>
    </flower>
    <flower id="16">
        <name>Hibiscus</name>
        <growing_tips photophilous="true">
            <temperature>25</temperature>
            <watering>650</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <origin>China</origin>
        <soil>Ground</soil>
        <visual_parameters>
            <stalk_color>light-green</stalk_color>
            <leaves_color>deep green</leaves_color>
            <average_size>47</average_size>
        </visual_parameters>
    </flower>

</flowers>
